// Note: The license below is based on the template at:
// http://opensource.org/licenses/BSD-3-Clause
// Copyright (C) 2020 Regents of the University of Texas
//All rights reserved.

// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:

// o Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.

// o Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the distribution.

// o Neither the name of the copyright holders nor the names of its
//   contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Original Author(s):
// Mertcan Temel         <mert@utexas.edu>

// DO NOT REMOVE:
// This file is generated by Temel's multiplier generator. Download from https://github.com/temelmertcan/multgen.

module DT_USP_RP_8x8_noX(
        input logic [7:0] IN1,
        input logic [7:0] IN2,
        output logic [15:0] result);
    
    
// Creating Partial Products 

    wire logic [7:0] pp0;
    wire logic [7:0] pp1;
    wire logic [7:0] pp2;
    wire logic [7:0] pp3;
    wire logic [7:0] pp4;
    wire logic [7:0] pp5;
    wire logic [7:0] pp6;
    wire logic [7:0] pp7;
    assign pp0 = {8{IN1[0]}} & IN2;
    assign pp1 = {8{IN1[1]}} & IN2;
    assign pp2 = {8{IN1[2]}} & IN2;
    assign pp3 = {8{IN1[3]}} & IN2;
    assign pp4 = {8{IN1[4]}} & IN2;
    assign pp5 = {8{IN1[5]}} & IN2;
    assign pp6 = {8{IN1[6]}} & IN2;
    assign pp7 = {8{IN1[7]}} & IN2;
    
    // The values to be summed in the summation tree, from LSB (left) to MSB:
     // pp0[0] pp0[1] pp0[2] pp0[3] pp0[4] pp0[5] pp0[6] pp0[7]   --     --     --     --     --     --     --   
     //   --   pp1[0] pp1[1] pp1[2] pp1[3] pp1[4] pp1[5] pp1[6] pp1[7]   --     --     --     --     --     --   
     //   --     --   pp2[0] pp2[1] pp2[2] pp2[3] pp2[4] pp2[5] pp2[6] pp2[7]   --     --     --     --     --   
     //   --     --     --   pp3[0] pp3[1] pp3[2] pp3[3] pp3[4] pp3[5] pp3[6] pp3[7]   --     --     --     --   
     //   --     --     --     --   pp4[0] pp4[1] pp4[2] pp4[3] pp4[4] pp4[5] pp4[6] pp4[7]   --     --     --   
     //   --     --     --     --     --   pp5[0] pp5[1] pp5[2] pp5[3] pp5[4] pp5[5] pp5[6] pp5[7]   --     --   
     //   --     --     --     --     --     --   pp6[0] pp6[1] pp6[2] pp6[3] pp6[4] pp6[5] pp6[6] pp6[7]   --   
     //   --     --     --     --     --     --     --   pp7[0] pp7[1] pp7[2] pp7[3] pp7[4] pp7[5] pp7[6] pp7[7] 
    
// Creating Summation Tree 

    
    // Dadda Summation Stage 1
    logic s0 ,c0;
    ha ha0 (pp0[6], pp1[5], s0, c0);
    logic s1 ,c1; 
    fa fa1 (pp0[7], pp1[6], pp2[5], s1, c1);
    logic s2 ,c2;
    ha ha2 (pp3[4], pp4[3], s2, c2);
    logic s3 ,c3; 
    fa fa3 (pp1[7], pp2[6], pp3[5], s3, c3);
    logic s4 ,c4;
    ha ha4 (pp4[4], pp5[3], s4, c4);
    logic s5 ,c5; 
    fa fa5 (pp2[7], pp3[6], pp4[5], s5, c5);
    
    // Dadda Summation Stage 2
    logic s6 ,c6;
    ha ha6 (pp0[4], pp1[3], s6, c6);
    logic s7 ,c7; 
    fa fa7 (pp0[5], pp1[4], pp2[3], s7, c7);
    logic s8 ,c8;
    ha ha8 (pp3[2], pp4[1], s8, c8);
    logic s9 ,c9; 
    fa fa9 (pp2[4], pp3[3], pp4[2], s9, c9);
    logic s10 ,c10; 
    fa fa10 (pp5[1], pp6[0], s0, s10, c10);
    logic s11 ,c11; 
    fa fa11 (pp5[2], pp6[1], pp7[0], s11, c11);
    logic s12 ,c12; 
    fa fa12 (c0, s1, s2, s12, c12);
    logic s13 ,c13; 
    fa fa13 (pp6[2], pp7[1], c1, s13, c13);
    logic s14 ,c14; 
    fa fa14 (c2, s3, s4, s14, c14);
    logic s15 ,c15; 
    fa fa15 (pp5[4], pp6[3], pp7[2], s15, c15);
    logic s16 ,c16; 
    fa fa16 (c3, c4, s5, s16, c16);
    logic s17 ,c17; 
    fa fa17 (pp3[7], pp4[6], pp5[5], s17, c17);
    logic s18 ,c18; 
    fa fa18 (pp6[4], pp7[3], c5, s18, c18);
    logic s19 ,c19; 
    fa fa19 (pp4[7], pp5[6], pp6[5], s19, c19);
    
    // Dadda Summation Stage 3
    logic s20 ,c20;
    ha ha20 (pp0[3], pp1[2], s20, c20);
    logic s21 ,c21; 
    fa fa21 (pp2[2], pp3[1], pp4[0], s21, c21);
    logic s22 ,c22; 
    fa fa22 (pp5[0], c6, s7, s22, c22);
    logic s23 ,c23; 
    fa fa23 (c7, c8, s9, s23, c23);
    logic s24 ,c24; 
    fa fa24 (c9, c10, s11, s24, c24);
    logic s25 ,c25; 
    fa fa25 (c11, c12, s13, s25, c25);
    logic s26 ,c26; 
    fa fa26 (c13, c14, s15, s26, c26);
    logic s27 ,c27; 
    fa fa27 (c15, c16, s17, s27, c27);
    logic s28 ,c28; 
    fa fa28 (pp7[4], c17, c18, s28, c28);
    logic s29 ,c29; 
    fa fa29 (pp5[7], pp6[6], pp7[5], s29, c29);
    
    // Dadda Summation Stage 4
    logic s30 ,c30;
    ha ha30 (pp0[2], pp1[1], s30, c30);
    logic s31 ,c31; 
    fa fa31 (pp2[1], pp3[0], s20, s31, c31);
    logic s32 ,c32; 
    fa fa32 (s6, c20, s21, s32, c32);
    logic s33 ,c33; 
    fa fa33 (s8, c21, s22, s33, c33);
    logic s34 ,c34; 
    fa fa34 (s10, c22, s23, s34, c34);
    logic s35 ,c35; 
    fa fa35 (s12, c23, s24, s35, c35);
    logic s36 ,c36; 
    fa fa36 (s14, c24, s25, s36, c36);
    logic s37 ,c37; 
    fa fa37 (s16, c25, s26, s37, c37);
    logic s38 ,c38; 
    fa fa38 (s18, c26, s27, s38, c38);
    logic s39 ,c39; 
    fa fa39 (s19, c27, s28, s39, c39);
    logic s40 ,c40; 
    fa fa40 (c19, c28, s29, s40, c40);
    logic s41 ,c41; 
    fa fa41 (pp6[7], pp7[6], c29, s41, c41);
    
    assign result[0] = pp0[0];
    logic [14:0] adder_result;
    RP_14 final_adder ({pp7[7], c40, c39, c38, c37, c36, c35, c34, c33, c32, c31, c30, pp2[0], pp0[1] }, {c41, s41, s40, s39, s38, s37, s36, s35, s34, s33, s32, s31, s30, pp1[0] }, adder_result );
    assign result[15:1] = adder_result[14:0];
endmodule



module RP_14 ( 
        input logic [13:0] IN1,
        input logic [13:0] IN2,
        output logic [14:0] OUT);
    
    logic C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14;
    ha m0 (IN1[0], IN2[0], OUT[0], C0);
    fa m1 (IN1[1], IN2[1], C0, OUT[1], C1);
    fa m2 (IN1[2], IN2[2], C1, OUT[2], C2);
    fa m3 (IN1[3], IN2[3], C2, OUT[3], C3);
    fa m4 (IN1[4], IN2[4], C3, OUT[4], C4);
    fa m5 (IN1[5], IN2[5], C4, OUT[5], C5);
    fa m6 (IN1[6], IN2[6], C5, OUT[6], C6);
    fa m7 (IN1[7], IN2[7], C6, OUT[7], C7);
    fa m8 (IN1[8], IN2[8], C7, OUT[8], C8);
    fa m9 (IN1[9], IN2[9], C8, OUT[9], C9);
    fa m10 (IN1[10], IN2[10], C9, OUT[10], C10);
    fa m11 (IN1[11], IN2[11], C10, OUT[11], C11);
    fa m12 (IN1[12], IN2[12], C11, OUT[12], C12);
    fa m13 (IN1[13], IN2[13], C12, OUT[13], C13);
    assign OUT[14] = C13;

endmodule

module ha (
        input logic a,
        input logic b,
        output logic s,
        output logic c);
    
    assign s = a ^ b;
    assign c = a & b;
endmodule



module fa (
        input logic x,
        input logic y,
        input logic z,
        output logic s,
        output logic c);
    
    assign s = x ^ y ^ z;
    assign c = (x & y) | (x & z) | (y & z);
endmodule

module Four2Two 
        #(parameter WIDTH=1) (
        input logic [WIDTH-1:0] in1,
        input logic [WIDTH-1:0] in2,
        input logic [WIDTH-1:0] in3,
        input logic [WIDTH-1:0] in4,
        input logic cin,
        output logic [WIDTH-1:0] sum,
        output logic [WIDTH-1:0] carry,
        output logic cout);
    
    wire logic [WIDTH:0] temp1;
    assign temp1 = {((in1 ^ in2)&in3 | in1 & ~(in1^in2)),cin};
    assign sum = ((in1 ^ in2) ^ in3 ^ in4) ^ temp1[WIDTH-1:0];
    assign carry = ((in1 ^ in2) ^ in3 ^ in4) & temp1[WIDTH-1:0] | in4 & ~((in1 ^ in2) ^ in3 ^ in4);
    assign cout = temp1[WIDTH];
endmodule




